<div style="text-align:left;font-size:2em"><span style="font-weight:bolder;font-size:1.25em">SP2273 | Learning Portfolio</span><br><br><span style="font-weight:bold;color:darkred">Storing Data (Good) Exercises</span></div>

## Exercise 1: More memory work
| **Term**   | **Brief description**                                                                                                                                               |
|------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Subsetting | Selecting an element within a list                                                                                                                                  |
| Indexing   | The number value (0 onwards) assigned to a specific element of a list/array *Actually is to select only 1 element, probably should have read the context clues*     |
| Slicing    | Selecting multiple elements within a list                                                                                                                           |
| Masking    | Creating a boolean list and using them to slice an array *Allows for subsetting by showing only those that are true*                                                |

## Exercise 2: Odd letters only


In [1]:
import numpy as np
np_array_2d = np.array([[1, "A"], [3, "C"], [2, "B"], [4, "D"],
                        [5, "E"], [7, "G"], [6, "F"], [8, "H"],
                        [10, "J"], [9, "I"]])
mask1 = np_array_2d[:,0].astype(int)%2 == 1
print(np_array_2d[mask1,1])

['A' 'C' 'E' 'G' 'I']


## Exercise 3

Objectives:
1. values below 50 to -1,
1. values above 50 to +1, and
1. values equal to 50 to 0

In [ ]:
lon = np.array([[66, 50, 57, -1, -1],
[92, -1, 88, -1, -1],
[75, -1, -1, 76, -1],
[-1, 51, 87, -1, -1],
[71, -1, 67, -1, 69]])
maskT = lon <=50
mask50 = lon == 50 # masks created first so that order doesn't matter
lon[maskT] = -1
lon[~maskT] = 1
lon[mask50] = 0 
print(lon)
lon == np.array([[1,  0,  1, -1, -1],
                [ 1, -1,  1, -1, -1],
                [ 1, -1, -1,  1, -1],
                [-1,  1,  1, -1, -1],
                [ 1, -1,  1, -1,  1]]) # Copy pasted from exercise to double check


[[ 1  0  1 -1 -1]
 [ 1 -1  1 -1 -1]
 [ 1 -1 -1  1 -1]
 [-1  1  1 -1 -1]
 [ 1 -1  1 -1  1]]


array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])